name: CI-Branch

on:
  push:
    branches-ignore: [ main ]

defaults:
  run:
    working-directory: v4

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: npm i
      - name: Test
        run: npm run test:unit
