name: CI

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: v4

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: npm i
      - name: Test
        run: npm run test:unit

  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      indexFilename: ${{ steps.setIndexName.outputs.indexFilename }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: npm i
      - name: Build latest version
        run: npm run build
      - name: Set index name
        id: setIndexName
        run: |
          cd dist
          FILE_NAME="index_v${GITHUB_RUN_NUMBER}.html"
          mv index.html $FILE_NAME
          echo "::set-output name=indexFilename::$(FILE_NAME)"
      - name: Upload dist as artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: v4/dist
          # retention-days: 1 
          # Auto deleted after 90 days: 
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration#artifact-and-log-retention-policy
        
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Download dist from build
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: v4/dist
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Backup old dist
        run: |
            aws s3 rm s3://${{ secrets.AWS_BUCKET }}/backup --recursive
            aws s3 mv s3://${{ secrets.AWS_BUCKET }} s3://${{ secrets.AWS_BUCKET }}/backup --recursive
      - name: Upload new dist
        run: aws s3 cp dist s3://${{ secrets.AWS_BUCKET }} --recursive

  deploy:
    runs-on: ubuntu-latest
    needs: [build, upload]
    
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Update distribution
        run: |
          aws cloudfront update-distribution --id ${{ secrets.DISTRIBUTION_ID }} \
          --default-root-object ${{needs.build.outputs.indexFilename}}
         
# Helpful links
# https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables
